### ISSUE TITLE
拓展程序

### ISSUE THREAD

**Issue by AAfish** [mengzonefire/dupan-rapid-extract#1]
你好，可以把这个发到谷歌拓展程序那里吗？不然添加不了~谢谢。

**Comment by mengzonefire** [comment]
你好，可以的，不太会弄谷歌拓展，能帮忙发上去的话非常感谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"AAfish"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月20日(星期一) 晚上10:27
收件人:&nbsp;"mengzonefire/dupan-rapid-extract"<dupan-rapid-extract@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[mengzonefire/dupan-rapid-extract] 拓展程序 (#1)





 
你好，可以把这个发到谷歌拓展程序那里吗？不然添加不了~谢谢。

**Comment by AAfish** [comment]
就是你发到谷歌商店里面去就行啦~

**Comment by AAfish** [comment]
楼主，那个秒传链接提取码是什么呀？

**Comment by AAfish** [comment]
原来这个不是用来下载度盘的呀。。。打扰了~

**Comment by mengzonefire** [comment]
close
